### ISSUE TITLE
用过的同类导航bar最好用和最易用的。但是似乎如果不用白色没法和statusbar配合

### ISSUE THREAD

**Issue by beiguancyc** [Bob1993/react-native-navigationbar#5]
![image](https://cloud.githubusercontent.com/assets/12932389/17589390/1f3155f6-6007-11e6-9d1e-820873b2c3e3.png)
ios下没找到让导航栏颜色扩展到状态栏的方法
后来又用statusbarPadding={false}，结果标题似乎重合了一些。

![image](https://cloud.githubusercontent.com/assets/12932389/17589929/03902126-600a-11e6-97ab-bc565462a113.png)

目前暂且把54行的white换成了this.props.barTintColor

**Comment by beiguancyc** [comment]
目前54行修改为
 <View style={{height: adaptiveStatusBar && this.props.statusbarPadding ? STATUS_BAR_HEIGHT : 0, backgroundColor: this.props.barTintColor}}/>

**Comment by poberwong** [comment]
Yeah, you are right. I used to show statusBar with `paddingTop` in the whole view. However, in order to make the statusBar dismiss automatically when the screen is placed landscape mode, I use a independent view instead and `onLayout` to get height of system statusBar to judge whether render the statusBar........... Lastly, it could be better to change it by yourself and pull request. I will respond your notification rapidly as soon as I receive it . Let's maintain the lib together ~ (下次尽量用英文问答问题，这样才能在Github上为更多的人提供帮助，谢谢合作，么么哒～)

**Comment by poberwong** [comment]
For one thing, it's pretty good to unite color of navigationBar and statusBar, for another, it must be a recommended way to control the statusBar with component 'StatusBar' provided by React Native. I'm waiting for you pull request. ~^_^~
